# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d6d7af8ec65df34676a71a52b64bbde902e0e94617f069083b21b4a8a92164b33d61deb5c43fd02899b16fea7b6424ff1ac57c88c3567e1af25595ef9fb2688

test:
  secret_key_base: 97729da2416862e86a422af3ed77acfd4652299ff883e0503daf29b5ff9399afff2c26ffd2d0134dfea4b8fec7a426e92f5cd20f84dffcc53c6b84797c9c581b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
