question1 = Question.create(content: "I like my neighbors")
question2 = Question.create(content: "I believe in democracy")
question3 = Question.create(content: "I'm worried for the next generation")
question4 = Question.create(content: "Kids deserve the best chance for their future")
question5 = Question.create(content: "Clean water and air are important for our health")
question6 = Question.create(content: "Women should be safe from domestic violence")
question7 = Question.create(content: "There should be limitations on the influence of corporate interests in elections")
question8 = Question.create(content: "I believe it's important to help people less fortunate than myself")

question9 = Question.create(content: "Everyone should be free to express themselves as they wish")
question10 = Question.create(content: "State and local government know how to best manage public lands")
question11 = Question.create(content: "America is a nation of immigrants")
question12 = Question.create(content: "We should pay less attention to problems overseas and concentrate on problems here at home")
question13 = Question.create(content: "It's worth investigating alternative energy sources to work towards energy independence")
question14 = Question.create(content: "Americans need to be willing to give up privacy and freedom in order to be safe from terrorism")
question15 = Question.create(content: "The government should do more to help needy Americans")
question16 = Question.create(content: "Stricter environmental laws and regulations cost too many jobs and hurt the economy")
question17 = Question.create(content: "Good diplomacy is the best way to ensure peace")
question18 = Question.create(content: "Most people who want to get ahead can make it if they're willing to work hard")

question19 = Question.create(content: "I like to discuss issues with others, even if we don't always agree")
question20 = Question.create(content: "I'm optimistic about the future")
